### ISSUE TITLE
Create a Notebook that works as tutorial for `payments-py` library

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/payments-py#5]
```[tasklist]
### Tasks
- [x] Identify the architecture of the solution (a solution without installing components is preferred)
- [x] Implement the notebook
- [x] Integrate into the tutorials page
```
